### ISSUE TITLE
Results of Softbot calibration

### ISSUE THREAD

**Issue by manuelgitgomes** [miguelriemoliveira/softbot#4]
Hello professor @miguelriemoliveira.

Where are the results of this calibration?

**Comment by manuelgitgomes** [comment]
Nevermind, saw issue #3

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira.

I saw the dataset and everything seemed fine.

The results are fine as well, with the RMS:

- rgb2rb (pix): 0.29
- lidar2rgb (pix): 4.4 and 4.8

However, the cross collection has very large errors:

- rgb2rb (pix): 36.3, 34.8, 32.5
- lidar2rgb (pix): 25.6 and 25.9

This seems very weird, as some pairs of collections have a very small error (sub pixel in rgb2rgb and about 3.5 pix in lidar2rgb), however, some collection pairs have a very large error (180 to almost 400 pixels).
I cannot find a pattern on these results so I testify if any collections are worsening the results, which would be weird and intra-collection results are fine.

The lidar2lidar cross collection is fine however, with an error of 0.06 meters.

This is even weirder because, when comparing with the real life results, the simulation ones are higher:
- rgb2rb (pix): 6.2, 6.7, 5.75
- lidar2rgb (pix): 9.9 and 9.5
- lidar2lidar (m): 0.03

How can we explain/solve this?

The results for the simulation and the real datasets are as follows:

[sim_softbot_results.tar.gz](https://github.com/miguelriemoliveira/softbot/files/12130058/sim_softbot_results.tar.gz)

[real_softbot_results.tar.gz](https://github.com/miguelriemoliveira/softbot/files/12130059/real_softbot_results.tar.gz)

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

this is strange. Can we talk? Are you available?

**Comment by manuelgitgomes** [comment]
Hello! The issue was solved when we verified that 4 collections were giving the largest errors.
To solve this, we added the collection selection function for every evaluation.
The new results are here:
[sim_softbot_results.tar.gz](https://github.com/miguelriemoliveira/softbot/files/12130690/sim_softbot_results.tar.gz)
